name = "DoonCraft Distance"
author = "DoonGuy"
version = "1.1.4a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a888278c3821ba09ee8b4b4d642dc65f08631f08e9950e5693c17f403b27ff46"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"
