name = "DoonCraft Distance"
author = "DoonGuy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0d0aea333aacbf06c58dbe0fee8a7e584b4e91ff353b43ef4b5555b21513779"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
