name = "DoonCraft Distance"
author = "DoonGuy"
version = "1.1.4a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfaf793b56e1128c65342b166cc28872ba55d91a398623b7bd211fe6475fecdb"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"
