name = "DoonCraft Distance"
author = "DoonGuy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e8ce427722782a3f795549a7044dac8283e5dd678b158854b8a913217233777"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
