name = "DoonCraft Distance"
author = "DoonGuy"
version = "1.1.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e9b4e3f8d62672d7873ccacc6112dc9eb4f455b26d1819270716d3293961b6c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
