name = "DoonCraft Distance"
author = "DoonGuy"
version = "1.1.2a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dd030ef2d18fd384e879e82a0b8bd5726269d439fa962619944ad3a1fefb6d3"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
