name = "DoonCraft Distance"
author = "DoonGuy"
version = "1.1.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f07e355340ca66472cc3ef8ae1f6f6ef8320b4fdf417eeb91135ba422c58001b"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
