name = "DoonCraft Distance"
author = "DoonGuy"
version = "1.1.2a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be22389aa52db1611e47c13ed14d7adbea0049fac0495cd9ecd28fd3a872bb30"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
